import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "../providers/next-ui/providers";
import StyledComponentsRegistry from "@/providers/antDesign/AntdRegistry";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <StyledComponentsRegistry>
          <Providers>{children}</Providers>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
